//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

var euler002 = (function() {
  'use strict';
  return {
    getFibonacci: getFibonacci
  };

  function getFibonacci(max) {
    var result = 0;
    var fib_2 = 2;
    var fib_1 = 1;
    while (fib_2 < max) {
      if (fib_2 % 2 == 0) result += fib_2;
      var next = fib_2 + fib_1;
      fib_1 = fib_2;
      fib_2 = next;
    }
    return result;
  }

})();
